import type { Menu } from "@/types/menu"

export const sampleMenu: Menu = {
  categories: [
    {
      id: 1,
      name: "Appetizers",
      description: "Start your meal with our delicious appetizers made with fresh, local ingredients",
      type: "food",
      items: [
        {
          id: 1,
          name: "Bruschetta Trio",
          prices: [{ label: "", value: 12.5 }],
          description: "Three varieties: classic tomato basil, mushroom truffle, and olive tapenade",
          icons: ["vegetarian"],
        },
        {
          id: 2,
          name: "Calamari Fritti",
          prices: [{ label: "", value: 14.0 }],
          description: "Crispy fried squid rings served with spicy marinara and lemon aioli",
          icons: ["seafood"],
        },
        {
          id: 3,
          name: "Caesar Salad",
          prices: [
            { label: "Small", value: 9.0 },
            { label: "Large", value: 14.0 },
          ],
          description: "Romaine lettuce, parmesan cheese, croutons, house-made caesar dressing",
          icons: ["vegetarian"],
        },
        {
          id: 4,
          name: "Antipasto Platter",
          prices: [{ label: "", value: 18.5 }],
          description: "Selection of cured meats, artisanal cheeses, olives, and marinated vegetables",
          icons: ["contains-nuts"],
        },
      ],
    },
    {
      id: 2,
      name: "Main Courses",
      description: "Our signature dishes crafted with premium ingredients and traditional techniques",
      type: "food",
      items: [
        {
          id: 5,
          name: "Grilled Atlantic Salmon",
          prices: [{ label: "", value: 26.0 }],
          description: "Fresh salmon fillet with lemon herb butter, quinoa pilaf, and seasonal vegetables",
          icons: ["seafood", "gluten-free"],
        },
        {
          id: 6,
          name: "Ribeye Steak",
          prices: [
            { label: "8oz", value: 32.0 },
            { label: "12oz", value: 42.0 },
          ],
          description: "Prime cut ribeye with garlic herb butter, truffle mashed potatoes, and asparagus",
          icons: ["gluten-free"],
        },
        {
          id: 7,
          name: "Vegetarian Risotto",
          prices: [{ label: "", value: 22.0 }],
          description: "Creamy arborio rice with wild mushrooms, roasted vegetables, and parmesan",
          icons: ["vegetarian", "gluten-free"],
        },
        {
          id: 8,
          name: "Chicken Parmigiana",
          prices: [{ label: "", value: 24.0 }],
          description: "Breaded chicken breast with marinara sauce, mozzarella, and spaghetti",
          icons: ["contains-eggs"],
        },
        {
          id: 9,
          name: "Pan-Seared Duck Breast",
          prices: [{ label: "", value: 28.0 }],
          description: "Five-spice duck breast with cherry gastrique and roasted root vegetables",
          icons: ["gluten-free"],
        },
        {
          id: 10,
          name: "Seafood Linguine",
          prices: [{ label: "", value: 25.0 }],
          description: "Fresh linguine with shrimp, scallops, mussels in white wine garlic sauce",
          icons: ["seafood"],
        },
      ],
    },
    {
      id: 3,
      name: "Desserts",
      description: "Sweet endings to complete your dining experience",
      type: "food",
      items: [
        {
          id: 11,
          name: "Tiramisu",
          prices: [{ label: "", value: 9.0 }],
          description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone cream",
          icons: ["contains-eggs", "vegetarian"],
        },
        {
          id: 12,
          name: "Chocolate Lava Cake",
          prices: [{ label: "", value: 10.0 }],
          description: "Warm chocolate cake with molten center, served with vanilla bean ice cream",
          icons: ["vegetarian", "contains-eggs"],
        },
        {
          id: 13,
          name: "Crème Brûlée",
          prices: [{ label: "", value: 8.5 }],
          description: "Vanilla custard with caramelized sugar crust and fresh berries",
          icons: ["vegetarian", "contains-eggs"],
        },
        {
          id: 14,
          name: "Gelato Selection",
          prices: [{ label: "", value: 7.0 }],
          description: "Three scoops of house-made gelato - ask your server for today's flavors",
          icons: ["vegetarian"],
        },
      ],
    },
    {
      id: 4,
      name: "Wine Selection",
      description: "Carefully curated wines from renowned vineyards around the world",
      type: "drink",
      items: [
        {
          id: 15,
          name: "Chianti Classico",
          prices: [
            { label: "Glass", value: 12.0 },
            { label: "Bottle", value: 45.0 },
          ],
          description: "Full-bodied red wine from Tuscany with notes of cherry and herbs",
          icons: ["vegan"],
        },
        {
          id: 16,
          name: "Pinot Grigio",
          prices: [
            { label: "Glass", value: 10.0 },
            { label: "Bottle", value: 38.0 },
          ],
          description: "Crisp white wine with citrus and green apple notes",
          icons: ["vegan"],
        },
        {
          id: 17,
          name: "Cabernet Sauvignon",
          prices: [
            { label: "Glass", value: 14.0 },
            { label: "Bottle", value: 52.0 },
          ],
          description: "Bold red wine with blackcurrant and oak flavors",
          icons: ["vegan"],
        },
        {
          id: 18,
          name: "Prosecco",
          prices: [
            { label: "Glass", value: 11.0 },
            { label: "Bottle", value: 42.0 },
          ],
          description: "Italian sparkling wine with delicate bubbles and floral notes",
          icons: ["vegan"],
        },
      ],
    },
    {
      id: 5,
      name: "Craft Cocktails",
      description: "Handcrafted cocktails made with premium spirits and fresh ingredients",
      type: "drink",
      items: [
        {
          id: 19,
          name: "Old Fashioned",
          prices: [{ label: "", value: 14.0 }],
          description: "Bourbon whiskey, sugar, Angostura bitters, orange peel",
          icons: ["vegan"],
        },
        {
          id: 20,
          name: "Classic Mojito",
          prices: [{ label: "", value: 12.0 }],
          description: "White rum, fresh mint, lime juice, sugar, soda water",
          icons: ["vegan"],
        },
        {
          id: 21,
          name: "Espresso Martini",
          prices: [{ label: "", value: 15.0 }],
          description: "Vodka, coffee liqueur, fresh espresso, simple syrup",
          icons: ["vegan"],
        },
        {
          id: 22,
          name: "Negroni",
          prices: [{ label: "", value: 13.0 }],
          description: "Gin, Campari, sweet vermouth, orange peel",
          icons: ["vegan"],
        },
      ],
    },
    {
      id: 6,
      name: "Non-Alcoholic Beverages",
      description: "Refreshing drinks for everyone to enjoy",
      type: "drink",
      items: [
        {
          id: 23,
          name: "Fresh Lemonade",
          prices: [{ label: "", value: 5.0 }],
          description: "House-made with fresh lemons, mint, and a touch of honey",
          icons: ["vegan"],
        },
        {
          id: 24,
          name: "Iced Tea",
          prices: [{ label: "", value: 4.0 }],
          description: "Black tea served over ice with fresh lemon",
          icons: ["vegan"],
        },
        {
          id: 25,
          name: "Sparkling Water",
          prices: [
            { label: "Small", value: 3.0 },
            { label: "Large", value: 5.0 },
          ],
          description: "San Pellegrino sparkling mineral water",
          icons: ["vegan"],
        },
        {
          id: 26,
          name: "Fresh Orange Juice",
          prices: [{ label: "", value: 6.0 }],
          description: "Freshly squeezed Valencia oranges",
          icons: ["vegan"],
        },
        {
          id: 27,
          name: "Coffee",
          prices: [
            { label: "Espresso", value: 3.5 },
            { label: "Americano", value: 4.0 },
            { label: "Cappuccino", value: 4.5 },
          ],
          description: "Premium Italian coffee beans, expertly roasted",
          icons: ["vegan"],
        },
      ],
    },
  ],
  pageBreaks: [],
}
